### ISSUE TITLE
Find easy way to setup k8s cluster on cloud provider VM

### ISSUE THREAD

**Issue by jwerak** [prgcont/workshop-k8s#24]
Choose and implement one of following options:
- managed kuberentes (azure, aws, gcp) 
  - do we have all privileges for cluster (rbac, etc)
- install k8s on cloud provider

**Comment by jwerak** [comment]
@tomkukral you have a lot of managed Azure K8s experience. Do you think this k8s cluster would be sufficient for our demos?

**Comment by dbecvarik** [comment]
Dont forget we need node access to show how stuff is mounted and explain internals. 
Also think about persistent volumes, and pricing.. We will pay for everything. So also do pricing report.

**Comment by tomkukral** [comment]
@jwerak try to avoid AKS as much as possible. 

We can start VMs and let them install Kubernetes via kubeadm. I'm using same setup for trainings and it works well. However, you have only single node cluster which make some demos impossible.

**Comment by jwerak** [comment]
I've created simplistic ansible + kubeadm installation on digitalocean here: https://github.com/prgcont/k8s-do

it creates cluster (1 master, 2 workers)
there is a simple script to:
- create namespace
- create serviceaccount
  - is everyone ok with this instead of real users? IMO there is no limitation
- create kube/config for each serviceaccount (context set for given namespace, so `--namespace` option is not needed when using `kubectl`)
- create rolebinding to grant admin for namespace 
TODO: 
- whatever cluster level rbac policies that we will need.
