### ISSUE TITLE
RBAC for shared envs

### ISSUE THREAD

**Issue by dbecvarik** [prgcont/workshop-k8s#25]
If we go to support workshop on shared envs, we should enable RBAC and limit people to their namespaces

**Comment by jwerak** [comment]
we will probably generate users/namespaces/kubeconfigs for users. 
The question is if we need some cluster level privileges for something. I think its separate issue that @Evalle will work on.

**Comment by jwerak** [comment]
for now DO setup has [script to grant user admin](https://github.com/prgcont/k8s-do/blob/master/scripts/create_sa_user.sh) for namespace.
