### ISSUE TITLE
explore infrastructure sponsorship for cloud provider

### ISSUE THREAD

**Issue by jwerak** [prgcont/workshop-k8s#27]
What do we need?
- cloud infra capable of running k8s and ideally with some native ingressing. 

What can we offer? (open for discussion - where do we draw the line)
- logo on slides,
- thanks in beginning? 
- other

several options are: 
- concur ?
- if someone can think of something, please comment.

**Comment by jwerak** [comment]
I will ask at work tomorrow what is the possibility from Concur.

**Comment by dbecvarik** [comment]
I would be against logo on each slide. We can give a slide and thanks.

**Comment by jwerak** [comment]
its doable, but we need to be some official entity...

**Comment by dbecvarik** [comment]
yep.. thats obvious its same for almost every company to sponsor us.

**Comment by dbecvarik** [comment]
@jwerak can we close it here and track on proper place?
