### ISSUE TITLE
replace echo by export

### ISSUE THREAD

**Issue by jtomsa** [prgcont/workshop-k8s#38]
> Now we can select one pod and execute:
> 
> $ echo POD_NAME=$(kubectl get pods | grep hello | cut -f 1 -d ' ' | head -n 1)
> $ kubectl exec -ti $POD_NAME touch /srv/test_file

-> export POD_NAME

**Comment by jtomsa** [comment]
(lesson-1)

**Comment by jwerak** [comment]
Fixed by #37
