### ISSUE TITLE
Istio 101

### ISSUE THREAD

**Issue by tomkukral** [prgcont/workshop-k8s#50]
The goal is to show Istio basic use cases and demonstrate basic functionality.

We will be using shared beefy Kubernetes cluster for all attendees. Plan is show them basics and then let them play with Istio and try bookinfo-like application.

Items to cover:
* How istio works
  * reuse image from https://medium.com/vescloud/battle-testing-istio-1-0-a0248ce68403
  * Sidecar, pilot, mixer, citadel
* How Istio was installed `kubectl apply -f istio-demo.yml`
* [Kiali](https://github.com/kiali/kiali) monitoring
* [Istio routing](https://istio.io/blog/2018/v1alpha3-routing/) vs Kubernetes ingress resource
* Basic resources: `Gateway`, `VirtualService`, `DestinationRule`, `ServiceEntry` and relations between them

@dbecvarik @pupapaik please add any ideas

**Comment by dbecvarik** [comment]
I can take whole kiali part. I think it would be also great if we can show some transaction tracing and maybe explain what you need to do to accomplish this.
